name: Build Android APK

on:
  push:
    branches: [ "main", "master", "hrm" ]
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 22

    - name: Install dependencies
      run: npm install

    - name: Build Web App
      run: CI=false npm run build

    - name: Sync Capacitor Android
      run: npx cap sync android

    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Grant execute permission for gradlew
      run: chmod +x android/gradlew

    - name: Build APK (Debug)
      working-directory: ./android
      run: ./gradlew assembleDebug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: FlowState-App
        path: android/app/build/outputs/apk/debug/app-debug.apk
